import 'dart:io';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:project_session/login.dart';
import 'package:project_session/Home.dart';
import 'package:project_session/sharedpref.dart';
import 'package:project_session/test.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'package:sqflite_common_ffi/sqflite_ffi.dart';



void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  await SharedPrefs.init();

  if (Platform.isWindows || Platform.isLinux || Platform.isMacOS) {
    sqfliteFfiInit();
    databaseFactory = databaseFactoryFfi;
  }
  final movies = [
    {
      "Name": "The Royal Tenenbaums",
      "Description": "Three gifted siblings reunite years later, each coping with disappointment, estrangement, and their eccentric father’s sudden illness.",
      "Rating": 4.1,
      "posterurl": ""
    },
    {
      "Name": "Moonrise Kingdom",
      "Description": "Two 12-year-olds run away together, throwing an island community into chaos in Wes Anderson’s tender ode to young love.",
      "Rating": 4.0,
      "posterurl": ""
    },
    {
      "Name": "Rushmore",
      "Description": "An eccentric teenager befriends a rich industrialist and falls for a first-grade teacher, sparking a strange love triangle.",
      "Rating": 3.9,
      "posterurl": ""
    },
    {
      "Name": "After Hours",
      "Description": "A New Yorker’s simple night out spirals into a surreal odyssey of bizarre encounters and escalating paranoia.",
      "Rating": 4.0,
      "posterurl": ""
    },
    {
      "Name": "The King of Comedy",
      "Description": "A delusional aspiring comedian kidnaps his idol in a desperate bid for fame.",
      "Rating": 4.2,
      "posterurl": ""
    },
    {
      "Name": "Bringing Out the Dead",
      "Description": "A burned-out paramedic in 1990s New York spirals through exhaustion, guilt, and hallucinations across sleepless nights.",
      "Rating": 3.8,
      "posterurl": ""
    },
    {
      "Name": "Pi",
      "Description": "A brilliant but paranoid mathematician believes he’s on the brink of discovering the key to the universe — and everyone wants it.",
      "Rating": 3.7,
      "posterurl": ""
    },
    {
      "Name": "Requiem for a Dream",
      "Description": "The descent of four people into obsession and addiction, told in haunting, surreal imagery.",
      "Rating": 4.3,
      "posterurl": ""
    },
    {
      "Name": "The Fountain",
      "Description": "Spanning a thousand years, a man searches for eternal love, battling mortality across past, present, and future.",
      "Rating": 3.6,
      "posterurl": ""
    },
    {
      "Name": "Black Swan",
      "Description": "A ballerina loses her grip on reality while chasing artistic perfection in Swan Lake.",
      "Rating": 4.4,
      "posterurl": ""
    },
    {
      "Name": "Punch-Drunk Love",
      "Description": "A lonely man with anger issues stumbles into love while being harassed by a scam call center.",
      "Rating": 4.0,
      "posterurl": ""
    },
    {
      "Name": "Magnolia",
      "Description": "The intersecting lives of broken souls in Los Angeles collide under the weight of chance, trauma, and forgiveness.",
      "Rating": 4.2,
      "posterurl": ""
    },
    {
      "Name": "The Master",
      "Description": "A WWII veteran drifter is taken under the wing of a charismatic cult leader in Paul Thomas Anderson’s haunting character study.",
      "Rating": 4.3,
      "posterurl": ""
    },
    {
      "Name": "A Serious Man",
      "Description": "A Midwestern professor’s life collapses in absurd ways as he questions faith, fate, and cosmic indifference.",
      "Rating": 4.0,
      "posterurl": ""
    },
    {
      "Name": "Inside Llewyn Davis",
      "Description": "A struggling folk singer in 1960s New York faces failure, heartbreak, and the randomness of luck.",
      "Rating": 4.2,
      "posterurl": ""
    },
    {
      "Name": "Blue Velvet",
      "Description": "A college student discovers a severed ear, pulling him into a world of corruption, violence, and dark desire.",
      "Rating": 4.4,
      "posterurl": ""
    },
    {
      "Name": "Mulholland Drive",
      "Description": "A Hollywood dream curdles into nightmare as an actress and an amnesiac chase identity and illusion.",
      "Rating": 4.5,
      "posterurl": ""
    },
    {
      "Name": "The Elephant Man",
      "Description": "A disfigured man in Victorian London endures cruelty and compassion in David Lynch’s most human film.",
      "Rating": 4.3,
      "posterurl": ""
    },
    {
      "Name": "Kundun",
      "Description": "Martin Scorsese’s meditative portrait of the Dalai Lama’s early life and exile from Tibet.",
      "Rating": 3.7,
      "posterurl": ""
    },
    {
      "Name": "The Life Aquatic with Steve Zissou",
      "Description": "An eccentric oceanographer goes on a bizarre revenge mission against the mythical shark that killed his partner.",
      "Rating": 3.8,
      "posterurl": ""
    },
  ];




  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
      ),
      home: SharedPrefs.isLoggedIn() ? HomeApp(title:SharedPrefs.getUsername()) : SigninApp(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int? name;

  @override
  void initState() {
    super.initState();

  }

  Future<void> _loadUserName() async {
    try {
      var doc = await FirebaseFirestore.instance
          .collection('users')
          .doc('2')
          .get();

      if (doc.exists) {
        setState(() {
          name = doc.get('age');
        });
      } else {
        setState(() {
          name = null;
        });
      }
    } catch (e) {
      print('Error loading user name: $e');
      setState(() {
        name = null;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          ElevatedButton(
            onPressed: () async {
              await FirebaseFirestore.instance.collection('users').add({
                'email': 'dommawalid@gmail.com',
                'password': '1234',
              });
            },
            child: const Text('John Cena'),
          )

          ,ElevatedButton(
            onPressed: () async {
              try {
                UserCredential user = await FirebaseAuth.instance
                    .signInWithEmailAndPassword(
                  email: 'dommawalid@gmail.com',
                  password: '123456',
                );

                if (user.user != null) {
                  // Get uid of the signed in user
                  String uid = user.user!.uid;

                  // Fetch extra data from Firestore
                  var doc = await FirebaseFirestore.instance
                      .collection('users')
                      .doc(uid)
                      .get();

                  if (doc.exists) {
                    print("Firestore Data: ${doc['name']}");
                  } else {
                    print("No Firestore doc for this user.");
                  }
                }
              } on FirebaseAuthException catch (e) {
                print("❌ Firebase Auth Error: ${e.code} - ${e.message}");
              } catch (e) {
                print("⚠️ Other Error: $e");
              }
            },
            child: const Text('Warinyyy'),
          )

        ],

      ),
    );
  }
}
